module.exports.chatbot = require("./src/chatbot")
module.exports.ytSearch = require("./src/ytSearch")
module.exports.reddit = require("./src/reddit")
module.exports.calculator = require("./src/calc")
module.exports.canvas = require("./src/canvas")